### ISSUE TITLE
They double our splinter

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#501]
4A098AE490813BF789427B940973
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2c532ca8-bd8a-43b8-807a-91cf909d655f)

With a minimum hand and waste in diamonds South should bid 4S.

When South Pass he is showing some interest and North should now XX to show a void and not just a little bit extra

**Comment by EdwardPiwowar** [comment]
Currently
pass - min 11-12 and 5=M
4M - 6M
XX - surplus
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7b62a5ac-a3c0-4b66-a7d0-8191cb2c1f51)

**Comment by ThorvaldAagaard** [comment]
It is better but, generally bidding what we have committed us for is weakest.
Pass = Extra but not 1st round control
XX = First round control
4M = Minimum

This is a rule, when ever they disturb our bidding. Bidding our comitted level is weakest
Like in 1Ma-(P)-Bergen-(X) 3Ma is weakest
1Ma - (P) - 2N Jacoby - (Overcall), now 4Ma is weakest

**Comment by ThePokerDude** [comment]
The bidding is better now but after forcing north to bid splinter south still passes instead of 4s and north still does not redouble.
![image](https://github.com/user-attachments/assets/0e1d0318-8912-4fab-b485-db502cbc0822)
![image](https://github.com/user-attachments/assets/17afcb4d-5ebd-466b-885f-c426ad65d185)
