### ISSUE TITLE
Something very wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#95]
1C3DDFC22E460816E645E3BC19A5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3a4ec1ae-567e-409a-83e1-3444a71b5a60)

I assume East grabbed the wrong bidding card

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/8eb5254f-81dc-48e4-b080-abbd7b897088)

**Comment by ThorvaldAagaard** [comment]
Not really.
Playing Inverted minors, it looks ok for 2/1 but not for SAYC

![image](https://github.com/user-attachments/assets/bae1f47e-16cd-48b8-8caf-780b6aa6082f)

And we still have the issue with inverted minors as West should bid 2NT

**Comment by EdwardPiwowar** [comment]
Maybe W should confirm fit.
